name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint (ruff) and type check (skip if not present)
        run: |
          pip install ruff || true
          ruff --version || true
          ruff check . || true
      - name: Run a quick import check
        run: |
          python -c "import sys; print('Python OK', sys.version)"
      - name: Validate Flask app imports
        run: |
          python -c "import importlib; importlib.import_module('app')"
